### ISSUE TITLE
[PE-D][Tester B] Display panel not updating on adding new tag

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W10-2/tp#225]
When adding a new tag, the display panel is not updated with the note's new tags
Edit: Bug also exists for clearing tags

![Recording 2023-11-03 at 16.57.03.gif](https://raw.githubusercontent.com/HEEaZ/ped/main/files/e24cd085-cd29-48c9-b848-6711c1313b9c.gif)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: HEEaZ/ped#7

**Comment by tjingsheng** [comment]
Fixed in https://github.com/AY2324S1-CS2103T-W10-2/tp/pull/236
Detail panel is now cleared after every command
