### ISSUE TITLE
[PE-D][Tester E] Selected item from list panel stays the same after other commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W10-2/tp#232]
![Screenshot 2023-11-03 at 5.02.54 PM.png](https://raw.githubusercontent.com/yihfei/ped/main/files/c1e43396-b61c-4926-9370-e37f5b1a3fb5.png)

After searching for mappings for cs3230, the last clicked mapping still remains, which slightly disorientating as I would expect the results to only display relevant mappings regardless of which panel.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: yihfei/ped#6

**Comment by tjingsheng** [comment]
will be fixed in https://github.com/AY2324S1-CS2103T-W10-2/tp/pull/236
