### ISSUE TITLE
[PE-D][Tester B] Note can only be added with 1 and only 1 tag

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W10-2/tp#233]
Notes can only be added with 1 tag. Cannot add node without tags, nor with more tags

Command format help given is slightly misleading, as it says `[tags]` when you can only really add 1 tag.

![Screenshot 2023-11-03 at 5.07.07 PM.png](https://raw.githubusercontent.com/HEEaZ/ped/main/files/5b6467f4-8073-4edf-aaac-7b1b3984241e.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: HEEaZ/ped#9

**Comment by lamchenghou** [comment]
@aliciamichellew I think we just need to change `tags` to `tag` (not sure if fixed in the new refactoring already). Also the missing space in `noteadd`.
