### ISSUE TITLE
[PE-D][Tester A] Partnercourse info not functioning

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W10-2/tp#235]
![Screenshot 2023-11-03 at 5.25.39 PM.png](https://raw.githubusercontent.com/Chrainx/ped/main/files/54168cf9-e291-4d23-bbd0-3cb4574ea895.png)
When clicking any partnercourse display detail does not change 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Chrainx/ped#8

**Comment by tjingsheng** [comment]
will be fixed in https://github.com/AY2324S1-CS2103T-W10-2/tp/pull/236
